// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { getHealth, getV1AuthMe, getV1Sites, getV1SitesBySiteIdExperiments, getV1SitesBySiteIdExperimentsByKey, getV1SitesBySiteIdExperimentsByKeyResults, type Options, postV1AuthLogin, postV1AuthSignup, postV1EventsConversion, postV1EventsExposure, postV1Sites, postV1SitesBySiteIdExperiments, postV1SitesBySiteIdExperimentsByKeyStatus } from '../sdk.gen';
import type { GetHealthData, GetHealthResponse, GetV1AuthMeData, GetV1AuthMeError, GetV1AuthMeResponse, GetV1SitesBySiteIdExperimentsByKeyData, GetV1SitesBySiteIdExperimentsByKeyError, GetV1SitesBySiteIdExperimentsByKeyResponse, GetV1SitesBySiteIdExperimentsByKeyResultsData, GetV1SitesBySiteIdExperimentsByKeyResultsError, GetV1SitesBySiteIdExperimentsByKeyResultsResponse, GetV1SitesBySiteIdExperimentsData, GetV1SitesBySiteIdExperimentsError, GetV1SitesBySiteIdExperimentsResponse, GetV1SitesData, GetV1SitesError, GetV1SitesResponse, PostV1AuthLoginData, PostV1AuthLoginError, PostV1AuthLoginResponse, PostV1AuthSignupData, PostV1AuthSignupError, PostV1AuthSignupResponse, PostV1EventsConversionData, PostV1EventsExposureData, PostV1SitesBySiteIdExperimentsByKeyStatusData, PostV1SitesBySiteIdExperimentsByKeyStatusError, PostV1SitesBySiteIdExperimentsByKeyStatusResponse, PostV1SitesBySiteIdExperimentsData, PostV1SitesBySiteIdExperimentsError, PostV1SitesBySiteIdExperimentsResponse, PostV1SitesData, PostV1SitesError, PostV1SitesResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getHealthQueryKey = (options?: Options<GetHealthData>) => createQueryKey('getHealth', options);

export const getHealthOptions = (options?: Options<GetHealthData>) => queryOptions<GetHealthResponse, AxiosError<DefaultError>, GetHealthResponse, ReturnType<typeof getHealthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getHealth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHealthQueryKey(options)
});

export const postV1AuthSignupMutation = (options?: Partial<Options<PostV1AuthSignupData>>): UseMutationOptions<PostV1AuthSignupResponse, AxiosError<PostV1AuthSignupError>, Options<PostV1AuthSignupData>> => {
    const mutationOptions: UseMutationOptions<PostV1AuthSignupResponse, AxiosError<PostV1AuthSignupError>, Options<PostV1AuthSignupData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postV1AuthSignup({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postV1AuthLoginMutation = (options?: Partial<Options<PostV1AuthLoginData>>): UseMutationOptions<PostV1AuthLoginResponse, AxiosError<PostV1AuthLoginError>, Options<PostV1AuthLoginData>> => {
    const mutationOptions: UseMutationOptions<PostV1AuthLoginResponse, AxiosError<PostV1AuthLoginError>, Options<PostV1AuthLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postV1AuthLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getV1AuthMeQueryKey = (options?: Options<GetV1AuthMeData>) => createQueryKey('getV1AuthMe', options);

export const getV1AuthMeOptions = (options?: Options<GetV1AuthMeData>) => queryOptions<GetV1AuthMeResponse, AxiosError<GetV1AuthMeError>, GetV1AuthMeResponse, ReturnType<typeof getV1AuthMeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getV1AuthMe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getV1AuthMeQueryKey(options)
});

export const getV1SitesQueryKey = (options?: Options<GetV1SitesData>) => createQueryKey('getV1Sites', options);

export const getV1SitesOptions = (options?: Options<GetV1SitesData>) => queryOptions<GetV1SitesResponse, AxiosError<GetV1SitesError>, GetV1SitesResponse, ReturnType<typeof getV1SitesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getV1Sites({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getV1SitesQueryKey(options)
});

export const postV1SitesMutation = (options?: Partial<Options<PostV1SitesData>>): UseMutationOptions<PostV1SitesResponse, AxiosError<PostV1SitesError>, Options<PostV1SitesData>> => {
    const mutationOptions: UseMutationOptions<PostV1SitesResponse, AxiosError<PostV1SitesError>, Options<PostV1SitesData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postV1Sites({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getV1SitesBySiteIdExperimentsQueryKey = (options: Options<GetV1SitesBySiteIdExperimentsData>) => createQueryKey('getV1SitesBySiteIdExperiments', options);

export const getV1SitesBySiteIdExperimentsOptions = (options: Options<GetV1SitesBySiteIdExperimentsData>) => queryOptions<GetV1SitesBySiteIdExperimentsResponse, AxiosError<GetV1SitesBySiteIdExperimentsError>, GetV1SitesBySiteIdExperimentsResponse, ReturnType<typeof getV1SitesBySiteIdExperimentsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getV1SitesBySiteIdExperiments({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getV1SitesBySiteIdExperimentsQueryKey(options)
});

export const postV1SitesBySiteIdExperimentsMutation = (options?: Partial<Options<PostV1SitesBySiteIdExperimentsData>>): UseMutationOptions<PostV1SitesBySiteIdExperimentsResponse, AxiosError<PostV1SitesBySiteIdExperimentsError>, Options<PostV1SitesBySiteIdExperimentsData>> => {
    const mutationOptions: UseMutationOptions<PostV1SitesBySiteIdExperimentsResponse, AxiosError<PostV1SitesBySiteIdExperimentsError>, Options<PostV1SitesBySiteIdExperimentsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postV1SitesBySiteIdExperiments({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getV1SitesBySiteIdExperimentsByKeyQueryKey = (options: Options<GetV1SitesBySiteIdExperimentsByKeyData>) => createQueryKey('getV1SitesBySiteIdExperimentsByKey', options);

export const getV1SitesBySiteIdExperimentsByKeyOptions = (options: Options<GetV1SitesBySiteIdExperimentsByKeyData>) => queryOptions<GetV1SitesBySiteIdExperimentsByKeyResponse, AxiosError<GetV1SitesBySiteIdExperimentsByKeyError>, GetV1SitesBySiteIdExperimentsByKeyResponse, ReturnType<typeof getV1SitesBySiteIdExperimentsByKeyQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getV1SitesBySiteIdExperimentsByKey({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getV1SitesBySiteIdExperimentsByKeyQueryKey(options)
});

export const postV1SitesBySiteIdExperimentsByKeyStatusMutation = (options?: Partial<Options<PostV1SitesBySiteIdExperimentsByKeyStatusData>>): UseMutationOptions<PostV1SitesBySiteIdExperimentsByKeyStatusResponse, AxiosError<PostV1SitesBySiteIdExperimentsByKeyStatusError>, Options<PostV1SitesBySiteIdExperimentsByKeyStatusData>> => {
    const mutationOptions: UseMutationOptions<PostV1SitesBySiteIdExperimentsByKeyStatusResponse, AxiosError<PostV1SitesBySiteIdExperimentsByKeyStatusError>, Options<PostV1SitesBySiteIdExperimentsByKeyStatusData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postV1SitesBySiteIdExperimentsByKeyStatus({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getV1SitesBySiteIdExperimentsByKeyResultsQueryKey = (options: Options<GetV1SitesBySiteIdExperimentsByKeyResultsData>) => createQueryKey('getV1SitesBySiteIdExperimentsByKeyResults', options);

export const getV1SitesBySiteIdExperimentsByKeyResultsOptions = (options: Options<GetV1SitesBySiteIdExperimentsByKeyResultsData>) => queryOptions<GetV1SitesBySiteIdExperimentsByKeyResultsResponse, AxiosError<GetV1SitesBySiteIdExperimentsByKeyResultsError>, GetV1SitesBySiteIdExperimentsByKeyResultsResponse, ReturnType<typeof getV1SitesBySiteIdExperimentsByKeyResultsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getV1SitesBySiteIdExperimentsByKeyResults({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getV1SitesBySiteIdExperimentsByKeyResultsQueryKey(options)
});

export const postV1EventsExposureMutation = (options?: Partial<Options<PostV1EventsExposureData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostV1EventsExposureData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostV1EventsExposureData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postV1EventsExposure({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postV1EventsConversionMutation = (options?: Partial<Options<PostV1EventsConversionData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostV1EventsConversionData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostV1EventsConversionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postV1EventsConversion({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
