// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetHealthData, GetHealthResponses, GetV1AuthMeData, GetV1AuthMeErrors, GetV1AuthMeResponses, GetV1SitesBySiteIdExperimentsByKeyResultsData, GetV1SitesBySiteIdExperimentsByKeyResultsErrors, GetV1SitesBySiteIdExperimentsByKeyResultsResponses, GetV1SitesBySiteIdExperimentsData, GetV1SitesBySiteIdExperimentsErrors, GetV1SitesBySiteIdExperimentsResponses, GetV1SitesData, GetV1SitesErrors, GetV1SitesResponses, PostV1AuthLoginData, PostV1AuthLoginErrors, PostV1AuthLoginResponses, PostV1AuthSignupData, PostV1AuthSignupErrors, PostV1AuthSignupResponses, PostV1EventsConversionData, PostV1EventsConversionResponses, PostV1EventsExposureData, PostV1EventsExposureResponses, PostV1SitesBySiteIdExperimentsByKeyStatusData, PostV1SitesBySiteIdExperimentsByKeyStatusErrors, PostV1SitesBySiteIdExperimentsByKeyStatusResponses, PostV1SitesBySiteIdExperimentsData, PostV1SitesBySiteIdExperimentsErrors, PostV1SitesBySiteIdExperimentsResponses, PostV1SitesData, PostV1SitesErrors, PostV1SitesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>): RequestResult<GetHealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/health',
    ...options
});

export const postV1AuthSignup = <ThrowOnError extends boolean = false>(options?: Options<PostV1AuthSignupData, ThrowOnError>): RequestResult<PostV1AuthSignupResponses, PostV1AuthSignupErrors, ThrowOnError> => (options?.client ?? client).post<PostV1AuthSignupResponses, PostV1AuthSignupErrors, ThrowOnError>({
    responseType: 'json',
    url: '/v1/auth/signup',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const postV1AuthLogin = <ThrowOnError extends boolean = false>(options?: Options<PostV1AuthLoginData, ThrowOnError>): RequestResult<PostV1AuthLoginResponses, PostV1AuthLoginErrors, ThrowOnError> => (options?.client ?? client).post<PostV1AuthLoginResponses, PostV1AuthLoginErrors, ThrowOnError>({
    responseType: 'json',
    url: '/v1/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const getV1AuthMe = <ThrowOnError extends boolean = false>(options?: Options<GetV1AuthMeData, ThrowOnError>): RequestResult<GetV1AuthMeResponses, GetV1AuthMeErrors, ThrowOnError> => (options?.client ?? client).get<GetV1AuthMeResponses, GetV1AuthMeErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/auth/me',
    ...options
});

export const getV1Sites = <ThrowOnError extends boolean = false>(options?: Options<GetV1SitesData, ThrowOnError>): RequestResult<GetV1SitesResponses, GetV1SitesErrors, ThrowOnError> => (options?.client ?? client).get<GetV1SitesResponses, GetV1SitesErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/sites',
    ...options
});

export const postV1Sites = <ThrowOnError extends boolean = false>(options?: Options<PostV1SitesData, ThrowOnError>): RequestResult<PostV1SitesResponses, PostV1SitesErrors, ThrowOnError> => (options?.client ?? client).post<PostV1SitesResponses, PostV1SitesErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/sites',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const getV1SitesBySiteIdExperiments = <ThrowOnError extends boolean = false>(options: Options<GetV1SitesBySiteIdExperimentsData, ThrowOnError>): RequestResult<GetV1SitesBySiteIdExperimentsResponses, GetV1SitesBySiteIdExperimentsErrors, ThrowOnError> => (options.client ?? client).get<GetV1SitesBySiteIdExperimentsResponses, GetV1SitesBySiteIdExperimentsErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/sites/{siteId}/experiments',
    ...options
});

export const postV1SitesBySiteIdExperiments = <ThrowOnError extends boolean = false>(options: Options<PostV1SitesBySiteIdExperimentsData, ThrowOnError>): RequestResult<PostV1SitesBySiteIdExperimentsResponses, PostV1SitesBySiteIdExperimentsErrors, ThrowOnError> => (options.client ?? client).post<PostV1SitesBySiteIdExperimentsResponses, PostV1SitesBySiteIdExperimentsErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/sites/{siteId}/experiments',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postV1SitesBySiteIdExperimentsByKeyStatus = <ThrowOnError extends boolean = false>(options: Options<PostV1SitesBySiteIdExperimentsByKeyStatusData, ThrowOnError>): RequestResult<PostV1SitesBySiteIdExperimentsByKeyStatusResponses, PostV1SitesBySiteIdExperimentsByKeyStatusErrors, ThrowOnError> => (options.client ?? client).post<PostV1SitesBySiteIdExperimentsByKeyStatusResponses, PostV1SitesBySiteIdExperimentsByKeyStatusErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/sites/{siteId}/experiments/{key}/status',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getV1SitesBySiteIdExperimentsByKeyResults = <ThrowOnError extends boolean = false>(options: Options<GetV1SitesBySiteIdExperimentsByKeyResultsData, ThrowOnError>): RequestResult<GetV1SitesBySiteIdExperimentsByKeyResultsResponses, GetV1SitesBySiteIdExperimentsByKeyResultsErrors, ThrowOnError> => (options.client ?? client).get<GetV1SitesBySiteIdExperimentsByKeyResultsResponses, GetV1SitesBySiteIdExperimentsByKeyResultsErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/sites/{siteId}/experiments/{key}/results',
    ...options
});

export const postV1EventsExposure = <ThrowOnError extends boolean = false>(options: Options<PostV1EventsExposureData, ThrowOnError>): RequestResult<PostV1EventsExposureResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostV1EventsExposureResponses, unknown, ThrowOnError>({
    url: '/v1/events/exposure',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postV1EventsConversion = <ThrowOnError extends boolean = false>(options: Options<PostV1EventsConversionData, ThrowOnError>): RequestResult<PostV1EventsConversionResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostV1EventsConversionResponses, unknown, ThrowOnError>({
    url: '/v1/events/conversion',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
