// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8787' | (string & {});
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Liveness check
     */
    200: {
        ok: true;
    };
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type PostV1AuthSignupData = {
    body?: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/v1/auth/signup';
};

export type PostV1AuthSignupErrors = {
    /**
     * Email already registered
     */
    409: {
        error: string;
    };
};

export type PostV1AuthSignupError = PostV1AuthSignupErrors[keyof PostV1AuthSignupErrors];

export type PostV1AuthSignupResponses = {
    /**
     * Account created
     */
    201: {
        id: string;
        email: string;
        createdAt: string;
    };
};

export type PostV1AuthSignupResponse = PostV1AuthSignupResponses[keyof PostV1AuthSignupResponses];

export type PostV1AuthLoginData = {
    body?: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/v1/auth/login';
};

export type PostV1AuthLoginErrors = {
    /**
     * Invalid email or password
     */
    401: {
        error: string;
    };
};

export type PostV1AuthLoginError = PostV1AuthLoginErrors[keyof PostV1AuthLoginErrors];

export type PostV1AuthLoginResponses = {
    /**
     * Signed JWT for the admin API
     */
    200: {
        token: string;
        expiresAt: string;
    };
};

export type PostV1AuthLoginResponse = PostV1AuthLoginResponses[keyof PostV1AuthLoginResponses];

export type GetV1AuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/auth/me';
};

export type GetV1AuthMeErrors = {
    /**
     * Unauthorized
     */
    401: {
        error: string;
    };
};

export type GetV1AuthMeError = GetV1AuthMeErrors[keyof GetV1AuthMeErrors];

export type GetV1AuthMeResponses = {
    /**
     * The authenticated user
     */
    200: {
        id: string;
        email: string;
        createdAt: string;
    };
};

export type GetV1AuthMeResponse = GetV1AuthMeResponses[keyof GetV1AuthMeResponses];

export type GetV1SitesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/sites';
};

export type GetV1SitesErrors = {
    /**
     * Unauthorized
     */
    401: {
        error: string;
    };
};

export type GetV1SitesError = GetV1SitesErrors[keyof GetV1SitesErrors];

export type GetV1SitesResponses = {
    /**
     * Sites owned by the authenticated user
     */
    200: Array<{
        id: string;
        name: string;
        apiKey: string;
        ownerUserId: string;
    }>;
};

export type GetV1SitesResponse = GetV1SitesResponses[keyof GetV1SitesResponses];

export type PostV1SitesData = {
    body?: {
        name: string;
    };
    path?: never;
    query?: never;
    url: '/v1/sites';
};

export type PostV1SitesErrors = {
    /**
     * Unauthorized
     */
    401: {
        error: string;
    };
};

export type PostV1SitesError = PostV1SitesErrors[keyof PostV1SitesErrors];

export type PostV1SitesResponses = {
    /**
     * Site created
     */
    201: {
        id: string;
        name: string;
        apiKey: string;
        ownerUserId: string;
    };
};

export type PostV1SitesResponse = PostV1SitesResponses[keyof PostV1SitesResponses];

export type GetV1SitesBySiteIdExperimentsData = {
    body?: never;
    path: {
        siteId: string;
    };
    query?: never;
    url: '/v1/sites/{siteId}/experiments';
};

export type GetV1SitesBySiteIdExperimentsErrors = {
    /**
     * Site not found
     */
    404: {
        error: string;
    };
};

export type GetV1SitesBySiteIdExperimentsError = GetV1SitesBySiteIdExperimentsErrors[keyof GetV1SitesBySiteIdExperimentsErrors];

export type GetV1SitesBySiteIdExperimentsResponses = {
    /**
     * Experiments for this site
     */
    200: Array<{
        id: string;
        siteId: string;
        key: string;
        version: number;
        status: 'draft' | 'running' | 'paused' | 'archived';
        trafficBp: number;
        createdAt: string;
        variants: Array<{
            id: string;
            key: string;
            weightBp: number;
            isControl: boolean;
            content: {
                [key: string]: unknown;
            };
        }>;
    }>;
};

export type GetV1SitesBySiteIdExperimentsResponse = GetV1SitesBySiteIdExperimentsResponses[keyof GetV1SitesBySiteIdExperimentsResponses];

export type PostV1SitesBySiteIdExperimentsData = {
    body?: {
        key: string;
        trafficBp?: number;
        variants: Array<{
            key: string;
            weightBp: number;
            isControl: boolean;
            content: {
                [key: string]: unknown;
            };
        }>;
    };
    path: {
        siteId: string;
    };
    query?: never;
    url: '/v1/sites/{siteId}/experiments';
};

export type PostV1SitesBySiteIdExperimentsErrors = {
    /**
     * Site not found
     */
    404: {
        error: string;
    };
    /**
     * Experiment key already exists for this site
     */
    409: {
        error: string;
    };
};

export type PostV1SitesBySiteIdExperimentsError = PostV1SitesBySiteIdExperimentsErrors[keyof PostV1SitesBySiteIdExperimentsErrors];

export type PostV1SitesBySiteIdExperimentsResponses = {
    /**
     * Experiment created
     */
    201: {
        id: string;
        siteId: string;
        key: string;
        version: number;
        status: 'draft' | 'running' | 'paused' | 'archived';
        trafficBp: number;
        createdAt: string;
        variants: Array<{
            id: string;
            key: string;
            weightBp: number;
            isControl: boolean;
            content: {
                [key: string]: unknown;
            };
        }>;
    };
};

export type PostV1SitesBySiteIdExperimentsResponse = PostV1SitesBySiteIdExperimentsResponses[keyof PostV1SitesBySiteIdExperimentsResponses];

export type GetV1SitesBySiteIdExperimentsByKeyData = {
    body?: never;
    path: {
        siteId: string;
        key: string;
    };
    query?: never;
    url: '/v1/sites/{siteId}/experiments/{key}';
};

export type GetV1SitesBySiteIdExperimentsByKeyErrors = {
    /**
     * Site or experiment not found
     */
    404: {
        error: string;
    };
};

export type GetV1SitesBySiteIdExperimentsByKeyError = GetV1SitesBySiteIdExperimentsByKeyErrors[keyof GetV1SitesBySiteIdExperimentsByKeyErrors];

export type GetV1SitesBySiteIdExperimentsByKeyResponses = {
    /**
     * The experiment
     */
    200: {
        id: string;
        siteId: string;
        key: string;
        version: number;
        status: 'draft' | 'running' | 'paused' | 'archived';
        trafficBp: number;
        createdAt: string;
        variants: Array<{
            id: string;
            key: string;
            weightBp: number;
            isControl: boolean;
            content: {
                [key: string]: unknown;
            };
        }>;
    };
};

export type GetV1SitesBySiteIdExperimentsByKeyResponse = GetV1SitesBySiteIdExperimentsByKeyResponses[keyof GetV1SitesBySiteIdExperimentsByKeyResponses];

export type PostV1SitesBySiteIdExperimentsByKeyStatusData = {
    body?: {
        status: 'running' | 'paused';
    };
    path: {
        siteId: string;
        key: string;
    };
    query?: never;
    url: '/v1/sites/{siteId}/experiments/{key}/status';
};

export type PostV1SitesBySiteIdExperimentsByKeyStatusErrors = {
    /**
     * Site or experiment not found
     */
    404: {
        error: string;
    };
};

export type PostV1SitesBySiteIdExperimentsByKeyStatusError = PostV1SitesBySiteIdExperimentsByKeyStatusErrors[keyof PostV1SitesBySiteIdExperimentsByKeyStatusErrors];

export type PostV1SitesBySiteIdExperimentsByKeyStatusResponses = {
    /**
     * Status updated
     */
    200: {
        id: string;
        siteId: string;
        key: string;
        version: number;
        status: 'draft' | 'running' | 'paused' | 'archived';
        trafficBp: number;
        createdAt: string;
        variants: Array<{
            id: string;
            key: string;
            weightBp: number;
            isControl: boolean;
            content: {
                [key: string]: unknown;
            };
        }>;
    };
};

export type PostV1SitesBySiteIdExperimentsByKeyStatusResponse = PostV1SitesBySiteIdExperimentsByKeyStatusResponses[keyof PostV1SitesBySiteIdExperimentsByKeyStatusResponses];

export type GetV1SitesBySiteIdExperimentsByKeyResultsData = {
    body?: never;
    path: {
        siteId: string;
        key: string;
    };
    query: {
        goal: string;
    };
    url: '/v1/sites/{siteId}/experiments/{key}/results';
};

export type GetV1SitesBySiteIdExperimentsByKeyResultsErrors = {
    /**
     * Site or experiment not found
     */
    404: {
        error: string;
    };
};

export type GetV1SitesBySiteIdExperimentsByKeyResultsError = GetV1SitesBySiteIdExperimentsByKeyResultsErrors[keyof GetV1SitesBySiteIdExperimentsByKeyResultsErrors];

export type GetV1SitesBySiteIdExperimentsByKeyResultsResponses = {
    /**
     * Per-variant results for the given goal
     */
    200: {
        goal: string;
        variants: Array<{
            key: string;
            isControl: boolean;
            exposures: number;
            conversions: number;
            rate: number;
            confidenceInterval: {
                lower: number;
                upper: number;
            };
            lift: number | null;
            pValue: number | null;
            significant: boolean | null;
        }>;
        srm: {
            chiSquared: number;
            degreesOfFreedom: number;
            detected: boolean;
        };
    };
};

export type GetV1SitesBySiteIdExperimentsByKeyResultsResponse = GetV1SitesBySiteIdExperimentsByKeyResultsResponses[keyof GetV1SitesBySiteIdExperimentsByKeyResultsResponses];

export type GetV1SitesBySiteIdGoalsData = {
    body?: never;
    path: {
        siteId: string;
    };
    query?: never;
    url: '/v1/sites/{siteId}/goals';
};

export type GetV1SitesBySiteIdGoalsErrors = {
    /**
     * Site not found
     */
    404: {
        error: string;
    };
};

export type GetV1SitesBySiteIdGoalsError = GetV1SitesBySiteIdGoalsErrors[keyof GetV1SitesBySiteIdGoalsErrors];

export type GetV1SitesBySiteIdGoalsResponses = {
    /**
     * Goal keys recorded for this site
     */
    200: Array<string>;
};

export type GetV1SitesBySiteIdGoalsResponse = GetV1SitesBySiteIdGoalsResponses[keyof GetV1SitesBySiteIdGoalsResponses];

export type PostV1EventsExposureData = {
    body?: {
        visitor_id: string;
        experiment: string;
        variant: string;
    };
    path?: never;
    query: {
        site_key: string;
    };
    url: '/v1/events/exposure';
};

export type PostV1EventsExposureResponses = {
    /**
     * Recorded (or silently dropped if the site/experiment aren't recognized)
     */
    202: unknown;
};

export type PostV1EventsConversionData = {
    body?: {
        visitor_id: string;
        goal: string;
    };
    path?: never;
    query: {
        site_key: string;
    };
    url: '/v1/events/conversion';
};

export type PostV1EventsConversionResponses = {
    /**
     * Recorded
     */
    202: unknown;
};
