import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

// Turns packages/snippet's build output into a plain TS string constant instead of
// importing the built .js file directly: Wrangler's bundler treats a `.js` import as
// code to parse and execute, not raw text, and coercing that (a custom module rule,
// forcing a non-standard extension) is real bundler-configuration risk for something
// this can sidestep entirely. A generated string constant needs no special handling
// from Wrangler, `wrangler dev`, or vitest-pool-workers — it's just TypeScript, same as
// every other import in this app. Mirrors control-plane's openapi.json generation:
// a plain Node script, run by Turborepo before the files that depend on its output.
const snippetDist = new URL("../../../packages/snippet/dist/snippet.global.js", import.meta.url);
const outDir = new URL("../src/generated/", import.meta.url);
const outFile = new URL("./snippet-source.ts", outDir);

const source = readFileSync(snippetDist, "utf-8");

mkdirSync(outDir, { recursive: true });
writeFileSync(
  outFile,
  `// Generated by scripts/build-snippet.ts from packages/snippet's build output — do not edit directly.\nexport const SNIPPET_SOURCE = ${JSON.stringify(source)};\n`,
);
